k9s:
  cluster: europa-dev.jupiter.myobdev.com
  namespace:
    active: kube-monitor
    lockFavorites: false
    favorites:
    - kube-monitor
    - all
  view:
    active: dp
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
