k9s:
  cluster: api.external.europa.jupiter.myob.com
  namespace:
    active: practice-corp-admin-shadow
    lockFavorites: false
    favorites:
    - practice-corp-admin-shadow
    - postgres-managed
    - payroll-shadow
    - kube-system
    - gm-digital-shadow
    - data-delivery-shadow
    - propelventures-shadow
    - sme-shadow
    - all
  view:
    active: ns
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
