k9s:
  cluster: api.external.europa-dev.jupiter.myobdev.com
  namespace:
    active: platform-enablement
    lockFavorites: false
    favorites:
    - platform-enablement
    - platform-enablement-shadow
    - kube-monitor
    - kube-system
    - all
  view:
    active: "no"
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
