k9s:
  cluster: api.external.europa-stg.jupiter.myobdev.com
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - workspace-2
    - workspace-1
    - workspace-1-shadow
    - platform-enablement-shadow
    - all
  view:
    active: ns
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
