k9s:
  cluster: arn:aws:eks:ap-southeast-2:763518865492:cluster/callisto-dev
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - kube-system
    - all
  view:
    active: dp
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
