k9s:
  cluster: api.external.europa.jupiter.myob.com
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - platform-enablement-shadow
    - kube-monitor
    - kube-system
    - all
  view:
    active: sqs
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
