k9s:
  cluster: europa-dev.jupiter.myobdev.com
  namespace:
    active: workspace-2-shadow
    lockFavorites: false
    favorites:
    - workspace-2-shadow
    - workspace-1-shadow
    - platform-enablement-shadow
    - platform-enablement
    - kube-ingress
    - kube-karpenter
    - all
  view:
    active: dp
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
