k9s:
  cluster: api.external.europa.jupiter.myob.com
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - tax
    - invoice-financing
    - arl
    - payroll
    - sme
    - sme-shadow
    - kube-karpenter
    - platform-enablement-shadow
    - all
    - kube-system
  view:
    active: dp
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
