k9s:
  cluster: api.external.europa-dev.jupiter.myobdev.com
  namespace:
    active: platform-enablement
    lockFavorites: false
    favorites:
    - platform-enablement
    - default
  view:
    active: deploy
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
