k9s:
  cluster: api.external.europa-dev.jupiter.myobdev.com
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - sme
    - payroll-shadow
    - data-delivery-shadow
    - all
  view:
    active: dp
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
